### PR TITLE
Add NRoot

### PR DESCRIPTION
**Pull request by uku1928**
You WERE considering adding it according to Discord.
oh I also updated readme

### CODE REVIEW

**Comment by uku1928** [comment]
this is the biggest PR I have ever done

**Comment by janIpen** [comment]
why

**Comment by uku1928** [comment]
why not

**Comment by janIpen** [comment]
no as in why is it your biggest pr
also how do i make / change cells?

**Comment by uku1928** [comment]
this one is my first real addition to the game: a new cell

also there should be Lua modding support soon (so that adding cells will be slightly easier)

**Review by IonutParau — COMMENTED** [review]
Looks good to me

**Pull request merged**
